services:
  web:
    # Запускаем "спящий режим", чтобы вручную управлять dev сервером
    command: sleep infinity

    # Чтобы получить доступ к исходному коду (до того, как Dockerfile обрежет его на стадии runner),
    # мы указываем собирать контейнер с базового этапа (где есть всё)
    build:
      context: ./Power-Paint-Web
      target: builder

    # В Dev Container мы обычно работаем из-под root
    user: root
